nginx-proxy:
  build: ./nginx-proxy/.
  container_name: nginx-proxy
  restart: always
  ports:
    # 80 should be open to the internet for letsencrypt purposes
    - "80:80"
    # 443 should be open to the internet for wss
    - "443:443"
  volumes:
    - /home/core/ssl-certs:/etc/nginx/certs:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
    DEFAULT_HOST: "musteka.la"

letsencrypt-nginx-proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt-nginx-proxy-companion
  restart: always
  volumes_from:
    - nginx-proxy
  volumes:
    - /home/core/ssl-certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro

ipld-eth-bridge:
  build: ../.
  container_name: ipld-eth-bridge
  restart: always
  expose:
    # This port is the one that nginx-proxy container will use to redirect calls
    # Has to be represented in the environment variable VIRTUAL_PORT below
    - "4003"
  ports:
    # 4001 is the ipfs swarm port
    - "4001:4002"
    # 5002 should be closed in the machine,
    # and is mapped so we can perform local diagnostics with curl
    - "5002:5002"
  volumes:
    - /home/core/ipfs-data:/www/ipfs-repo
  links:
    - parity
  environment:
    ETH_HOST: "parity"
    ETH_PORT: "5001"
    VIRTUAL_HOST: "${HOSTNAME}.musteka.la"
    VIRTUAL_PORT: "4003"
    LETSENCRYPT_HOST: "${HOSTNAME}.musteka.la"
    LETSENCRYPT_EMAIL: "admin@musteka.la"

parity:
  image: parity/parity:stable
  container_name: parity
  restart: always
  ports:
    # 5001 will be used by the bridge
    # Should be closed in the machine,
    # and is mapped so we can perform local diagnostics with curl
    - "5001:5001"
    # 30303 is the RLPx port, should be open to the internet
    - "30303:30303"
    # JSON RPC Port
    - "8545:8545"
  volumes:
    - /home/core/parity-data:/parity-data
    - /home/core/peers:/parity-peers
  command: "--no-ancient-blocks --no-serve-light --max-peers 250 --snapshot-peers 50 --min-peers 50 --mode active --tracing off --pruning fast --db-compaction ssd --cache-size 4096 --datadir /parity-data --cache 8192 --ipfs-api --ipfs-api-port 5001 --ipfs-api-hosts all --ipfs-api-interface 0.0.0.0 --jsonrpc-apis=all --jsonrpc-interface=0.0.0.0"
